# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Execute tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'ref/heads/main'

    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_PROJECT_KEY }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
